Element web 2022 code style guide
vector-im/element-meta pull request #216
Opened 2022-04-09 06:28 UTC by turt2live

I needed somewhere where all web team members can review this and see changes from the original internal doc, so picked here. If this repo is not the best place for this then will move it after review has been fully addressed.

For those not on the web team: feel free to mute this PR using the unsubscribe button to the right, and sorry for the noise.

2022-04-09 06:30 UTC, turt2live commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
Question: do we care about import ordering still?

2022-04-09 06:45 UTC, SimonBrandner commented on web-code-style.md
> +    }
Should we do this?

```ts
    function doThing(
        arg1: string, arg2: string, arg3: string,
    ): boolean {
        return !!arg1 && !!arg2 && !!arg3;
    }
```

2022-04-11 11:32 UTC, jryans commented on web-code-style.md
> +This code style applies to projects which the element-web team directly maintains or is reasonably
Assuming this does land over here, we should remove https://github.com/matrix-org/matrix-react-sdk/blob/master/code_style.md and also updating contributing docs at all layers to point here.

2022-04-11 15:39 UTC, turt2live commented on web-code-style.md
> +This code style applies to projects which the element-web team directly maintains or is reasonably
plan is to do that, but first get alignment + find a home for it to live.

2022-04-13 20:09 UTC, turt2live commented
looking for checkmarks from at least the people requested, though if I've missed anyone or people have opinions then please raise them.

2022-04-13 20:12 UTC, turt2live commented on web-code-style.md
> +    }
I personal prefer the shorter lines, but I am aware of past opinions on this being more in favour of what's in the doc.

2022-04-14 05:56 UTC, SimonBrandner reviewed
Otherwise looks awesome!

2022-04-14 05:56 UTC, SimonBrandner commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
NIT: I am having a bit of trouble parsing this - how could a single-line block have newlines?

2022-04-14 05:56 UTC, SimonBrandner commented on web-code-style.md
> +1. Types for lifecycle functions are not required (render, componentDidMount, etc).
Why not type them? What about member visibility?

2022-04-14 05:56 UTC, SimonBrandner commented on web-code-style.md
> +   component. The utility component should not be exported.
Does this apply to function components aswell? I think we don't really follow this rule for them and it often wouldn't exactly make sense to do so?

2022-04-14 05:56 UTC, SimonBrandner commented on web-code-style.md
> +        >{ _t("Short string here") }</Component>;
This looks a little odd but I guess it's a personal preference?

2022-04-14 05:56 UTC, SimonBrandner commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
I think we don't tend to make spaces here or is it just in my head? :sweat_smile: 

```suggestion
        &.mx_MyFoo_avatar { // instead of &_avatar
```

2022-04-14 10:53 UTC, justjanne approved these changes

2022-04-14 10:53 UTC, justjanne commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
Do we care about how these lines would get wrapped? e.g.,

```typescript
function doThing(
    arg1: string,
    arg2: string,
    arg3: string,
): boolean {
    return !!arg1 &&
        !!arg2 &&
        !!arg3;
    }
```

2022-04-14 10:53 UTC, justjanne commented on web-code-style.md
> +    ```
Also, do we care about how we’d wrap long function calls? e.g.,

```typescript
    something.doThing()
        .doOtherThing()
        .doMore()
        .somethingElse(it =>
            useIt(it)
        );
```

2022-04-14 10:53 UTC, justjanne commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
Is there a functional reason for this, or is this just personal preference?

2022-04-14 11:03 UTC, SimonBrandner commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
Preference, as far as I can remember

2022-04-14 11:03 UTC, SimonBrandner commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
I think it's nice to wrap these in brackets so that they can be aligned

2022-04-14 12:33 UTC, turt2live commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
this is banned:

```
if (condition)
    return true;
```

it needs to be on a single line, or contain curly brackets

2022-04-14 12:34 UTC, turt2live commented on web-code-style.md
> +1. Types for lifecycle functions are not required (render, componentDidMount, etc).
member visibility is now required on them (previously wasn't, but having some functions with member visibility and some not prevents us from turning on the linter in a reasonable way). Types aren't required because they're overrides, so can be inherited safely.

2022-04-14 12:35 UTC, turt2live commented on web-code-style.md
> +   component. The utility component should not be exported.
It would apply, yes. One exported component per file, but files can contain multiple components (so long as only one of them is exported).

2022-04-14 12:36 UTC, turt2live commented on web-code-style.md
> +        >{ _t("Short string here") }</Component>;
We have code like this in the codebase, so it returns to the mission statement of "current code + 10%" rather than "definitely better" :p

2022-04-14 12:37 UTC, turt2live commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
The space has significant meaning - not really sure if it's correct in the example or not, but hopefully somewhat clear :p

2022-04-14 12:38 UTC, turt2live commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
we seem to be missing a rule that says the boolean operators are on the start of the line, so would look like this:
```typescript
function doThing(
    arg1: string,
    arg2: string,
    arg3: string,
): boolean {
    return !!arg1
        && !!arg2
        && !!arg3;
}
```

2022-04-14 12:38 UTC, turt2live commented on web-code-style.md
> +    ```
yes, we do. As described by your comment :)

2022-04-14 12:39 UTC, turt2live commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
This is from the historical code style - I'd be happy to rip it out, but it's also caused enough fights in the past where it should be written down.

2022-04-14 13:12 UTC, kerryarchibald commented on web-code-style.md
> +11. Interface names begin with an uppercase i.
I thought we voted to remove this?

2022-04-14 13:20 UTC, SimonBrandner commented on web-code-style.md
> +   component. The utility component should not be exported.
Ah, makes sense - _resolved_

2022-04-14 13:20 UTC, SimonBrandner commented on web-code-style.md
> +1. Types for lifecycle functions are not required (render, componentDidMount, etc).
Ah, makes sense - _resolved_

2022-04-14 13:20 UTC, SimonBrandner commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
I think this would be clearer?

```suggestion
5. Single-line blocks are permitted, so long as they don't contain curly brackets.
```

2022-04-14 13:20 UTC, SimonBrandner commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
Oh, my bad, I was confused, sorry for the noise - _resolved_

2022-04-14 15:55 UTC, dbkr reviewed
I think this seems basically fine although honestly it's quite a lot to process in one go. Probably a bit late for this now, but I might have suggested making the lint rules canon rather than a doc, as I think this is realistically too long to be easily digested.

2022-04-14 15:59 UTC, turt2live commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
it's the newline that's the issue though? We also don't mind if someone write `if (x) { return y; }`

2022-04-14 16:00 UTC, turt2live commented on web-code-style.md
> +11. Interface names begin with an uppercase i.
we did - good spot.

2022-04-14 16:03 UTC, turt2live commented
@dbkr "generally fine" is about the best this doc can expect - there's almost certainly going to be things that come up in the process of converting doc to lint rules which will require further discussion. At this stage, I'm hoping to get general approval to avoid iterating on lint rules because that's a more awful place to rapidly iterate within.

2022-04-14 16:07 UTC, SimonBrandner commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
The problem I have is that the meaning of _single-line block_ isn't clear to me - a single-line block can't have newlines by definition, right? I might be just misunderstanding what it means...

Anyway, this is turning into a wasted time on discussing unimportant details... :sweat_smile: Be sure to count this as resolved, if it's clear to other people

2022-04-14 16:08 UTC, SimonBrandner commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
IIRC, we used to have both in the codebase but then decided to choose one to be consistent?

2022-04-14 16:09 UTC, turt2live commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
We can figure out the wording, yea. It's trying to make what I mentioned earlier illegal, but the doc is intentionally framed in positive affirmations :p

2022-04-17 03:57 UTC, robintown commented on web-code-style.md
> +## (S)CSS
Should we require comments explaining use of `!important`?

2022-04-19 08:45 UTC, germain-gg approved these changes
Overall looks good to me, I've added a few things that could use a bit of attention regarding the CSS codebase

2022-04-19 08:45 UTC, germain-gg commented on web-code-style.md
> +## (S)CSS
I'd recommend to rename this as we are not using SCSS despite the file extension we use.
We use plain CSS with a lot of PostCSS plugins. But in fact we do not have all the features available in Sass

2022-04-19 08:45 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
I don't think we should ever define the context in which it's used. It's break reusability
Classes should define the function of the element and not the context in which it's used.

2022-04-19 08:45 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
This look very very very close to BEM, but is not just quite right.
If we want to adopt this style of writing CSS, should we recommend using BEM as it's well documented and explained?

Line `3` would be changed to `mx_MyFoo__avatar--user`

2022-04-19 08:45 UTC, gsouquet commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
I'm not convinced of this code style rule. But more importantly I would have no idea as a developer how to determine whether a variable is shared or not (not actually sure what that means?)

2022-04-19 08:45 UTC, gsouquet commented on web-code-style.md
> +9. Use and define generic mixins when reusing styles a lot.
We should document here that we are using PostCSS mixins and not the classic Sass ones

2022-04-19 11:47 UTC, andybalaam commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
How about `Blocks without curly braces are permitted only when they don't contain newlines.`

2022-04-19 11:53 UTC, andybalaam approved these changes

2022-04-19 11:55 UTC, t3chguy approved these changes

2022-04-19 13:44 UTC, duxovni requested changes

2022-04-19 13:44 UTC, duxovni commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
`When a statement's body is a single line, it may be written without curly braces, so long as the body is placed on the same line as the statement`?

2022-04-19 13:44 UTC, duxovni commented on web-code-style.md
> +        type Options = IMyObject | string;
For consistency with our new interface naming policy, we should probably remove the `I` here.

2022-04-19 13:44 UTC, duxovni commented on web-code-style.md
> +   instead.
We should remove `I` from these too, right?

2022-04-20 05:08 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
This seems like a good thing to do, though our current code is heavily biased against the idea of purpose. For the style guide here, I think it'd be best to move forward with the context model and consider changing our CSS structure for a future, more desirable-shaped, style guide.

2022-04-20 05:09 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
sorry, what is BEM? I don't imagine it's Blackberry Enterprise Manager, which is what my brain is autocompleting here.

2022-04-20 05:10 UTC, turt2live commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
fwiw, this is an attempt at standardizing what is in the code already - I'm very much not opposed to picking a naming convention and sticking with it.

2022-04-20 06:20 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
Block, Element, Modifier => https://css-tricks.com/bem-101/

2022-04-20 06:21 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
But this is another case of the `I` prefixed interfaces in TypeScript. Our codebase is heavily influenced one way but in here we give advices to do the right thing.
If we have a style guide saying this, I'm not sure we'd ever be able to move the needle here

2022-04-20 06:23 UTC, gsouquet commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
Regardless of naming conventions, I'm not sure what a "shared" variable is, and how as a developer I can figure out whether I need to use lower camel case or dashed naming

2022-04-22 19:22 UTC, SimonBrandner commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
Yep, that's it - thanks!

2022-04-25 07:59 UTC, gsouquet commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
Given the code comment the space should not be needed, as it says we should not use `&` to make the selector shorter, but we should instead optimise for readibility

2022-04-26 04:34 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
sorry, I meant we have both in the code and picking one is a valid option: just not sure if we have an easy way to do that picking.

2022-04-26 04:36 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
I'd like to see more thoughts on this before we make a choice.

2022-04-26 04:36 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
Closing this thread in favour of https://github.com/vector-im/element-meta/pull/216#discussion_r852729609

2022-04-26 04:37 UTC, turt2live commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
sorry, for clarity: picking one over the other is entirely valid, though making that decision is quite challenging. If we can figure out which one we want everywhere, let's do that. Otherwise, we can fix the wording here to better define when something is "shared".

2022-05-03 10:46 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
It looks like no one is very opiniated about this even after discussing during the previous weekly team meeting.
I believe we should go ahead with this as this improves maintainability by a great deal and no one seems to have reasons to decide against

2022-05-03 15:29 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
I honestly don't see the minutes for that discussion, but agreed that people don't seem to care enough to leave a comment.  

For clarity, is your suggestion to drop the `--user` bit from the style guide?

2022-05-04 10:34 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
There was none, we asked people to comment on this.

No the idea is not to drop the `--xxx` bit, as this is aligned with what the BEM methodology suggests (which we are loosely following).

What I believe is that we should codify the naming of our CSS classes. In here it describes in which context it's used rather than what it does.
We use a lot of the time CSS classes like `mx_SpotlightDialog_input` (sorry this is the last example I have in mind), where this input has nothing to do with the spotlight dialog, which means that we will never be able to re-use that borderless edge-to-edge input in a different context.

We should favour the function of the component in naming rather than where it is used

2022-05-04 16:17 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
I'm failing to follow the proposed change, sorry. The doc here describes what we already do? BEM would be a different approach that I'd have expected some discussion on...

Is there a file which already exists that demonstrates what you're proposing we use for the code style?

2022-05-05 03:44 UTC, turt2live commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
answer: yes, for now. The value is mostly in merge conflicts avoidance at the moment, and people have their IDEs set up to deal with it.

2022-05-05 07:12 UTC, gsouquet commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
The other discussion is not a duplicate, it's proposing something else.
We're currently using a CSS naming convention that is oddly close to BEM, but not quite. What I recommend is that we actually formalise that we'd like to use that, because that way we benefit from all the documentation that already exists in the CSS ecosystem for this tried and tested methodology

2022-05-05 07:14 UTC, gsouquet commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
I'm not talking about BEM at all in this thread.

I'm talking about how this example is a classic example of how we incorrectly (in my opinion) name classes. We name them based on where they are used rather than what they are. This breaks reusability and my proposal is to add some guidance in our style guide on naming to avoid this kind of patterns in the future

2022-05-12 05:46 UTC, turt2live commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
From internal discussion I believe we've determined that BEM is the way forward. Will codify this.

If this is an inaccurate representation of the conversation, please raise the concern loudly and urgently.

2022-05-12 15:48 UTC, kerryarchibald approved these changes

2022-05-12 15:48 UTC, duxovni commented
Do we have any official stance on double-quoted vs single-quoted strings in JS?

2022-05-12 16:29 UTC, turt2live commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
@duxovni says:

> Do we have any official stance on double-quoted vs single-quoted strings in JS?

2022-05-12 16:29 UTC, turt2live commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
Generally I think we prefer double quotes for strings and use single quotes strategically. For example: single quotes on empty strings to reduce confusion/noise.

2022-05-20 06:39 UTC, weeman1337 commented on web-code-style.md
> +1. 120 character limit per line. Match existing code in the file if it is using a lower guide.
Should we add some info about the licence header (+ link to a template)?

2022-05-20 06:42 UTC, weeman1337 commented on web-code-style.md
> +36. File ordering is not strict, but should generally follow this sequence:
Should we add 1. licence header (+ newline) here?  

If we want to define an ESLint rule covering that we can have a look at https://github.com/Stuk/eslint-plugin-header . It supports patterns. Means we can configure a flexible year so that we don't have to update that.

2022-05-20 14:08 UTC, turt2live commented on web-code-style.md
> +1. 120 character limit per line. Match existing code in the file if it is using a lower guide.
Will use the other thread to track this as a reminder.

2022-05-21 12:56 UTC, t3chguy commented on web-code-style.md
> +# Element Web/Desktop code style
What about promise-chaining (then/catch/finally) vs async-await

2022-05-21 12:56 UTC, t3chguy commented on web-code-style.md
> +# Element Web/Desktop code style
What about `React.Component::forceUpdate`? I think it should be barred from all new code, it makes it too easy to miss data updates

2022-06-08 08:52 UTC, luixxiul commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
One of the issues, tiny or not, is that with BEM style the class name can be quite long if the component name is already long. This issue could be avoided with using shorthand ([see](https://mattstauffer.com/blog/organizing-css-oocss-smacss-and-bem/)), which will not happen though.

2022-07-08 08:51 UTC, gsouquet commented on web-code-style.md
> +9. Use and define generic mixins when reusing styles a lot.
Adding here that we should discourage the use of mixins as they are non standard and I am challenging their usefulness in our codebase.

CSS composition will for the very large majority of cases fit the bill

2022-07-08 10:41 UTC, kerryarchibald commented on web-code-style.md
> +9. Use and define generic mixins when reusing styles a lot.
I'd also vote that we should remove this - if styles are being reused we should favour component composition

2022-07-08 11:11 UTC, luixxiul commented on web-code-style.md
> +4. Keep indentation/nesting to a minimum. Maximum suggested nesting is 5 layers.
Could I know the reason why the number should be five, not six or seven? IMHO if the number which looks arbitrary is chosen, the reason for it should be mentioned.

2022-07-13 16:28 UTC, kerryarchibald commented on web-code-style.md
> +    const val = a > b
We should add a point about operator linebreak for non-ternary expressions. `After` behaviour appears to be most common in our codebases.
Enabling operator-linebreak rule https://github.com/matrix-org/eslint-plugin-matrix-org/pull/26

2022-07-13 16:51 UTC, turt2live commented on web-code-style.md
> +    const val = a > b
fwiw, the examples in this doc are normative. The proposal was to align on the behaviour shown here.

2022-07-14 12:30 UTC, weeman1337 commented on web-code-style.md
> +11. Interface names begin with an uppercase i.
Should we write `Interface names must not begin with an uppercase i.`? Otherwise discussions start whether a leading `I` is OK or not.

2022-07-14 12:52 UTC, weeman1337 commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
We should re-work this example because `& .mx_MyFoo_avatar` selects descendants  of `.mx_MyFoo` while `&_avatar` doesn't. Or is the PCSS behaving differently?

2022-07-14 16:38 UTC, duxovni commented on web-code-style.md
> +5. Single-line blocks are permitted, so long as they don't use newlines.
Turning my proposal above into a suggestion we can directly apply, since people seem to be in support.
```suggestion
5. When a statement's body is a single line, it may be written without curly braces, so long as the body is placed on the same line as the statement.
```

2022-07-14 16:42 UTC, duxovni commented on web-code-style.md
> +    interface ITest {
```suggestion
    interface Test {
```

2022-07-14 16:46 UTC, duxovni commented on web-code-style.md
> +11. Interface names begin with an uppercase i.
```suggestion
11. Interface names should not be marked with an uppercase `I`.
```

2022-07-18 13:09 UTC, weeman1337 commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
Already part of the doc: https://github.com/vector-im/element-meta/pull/216/files#diff-97f46bd1ed0e6dfce7a7002e96f72ecd446b90c5eb5f48d687dc2d9df856290cR241

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +# Element Web/Desktop code style
**Vote:** Should promise-chaining be preferred to async-await?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +# Element Web/Desktop code style
**Vote:** Should async-await be preferred to promise-chaining?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +# Element Web/Desktop code style
**Vote:** Should `React.Component::forceUpdate` be barred from new code?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
**Vote:** Should we prefer double quotes to single quotes?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
**Vote:** Should we add a rule that operators must be at the beginning of the line?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +    ```
Added to the doc.

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
**Vote:** We should prefer to pad curly braces with a single space in JSX and properties.

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
**Vote:** We should prefer **not** to pad curly braces with space in JSX and properties
(opposite of the question above).

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
**Vote:** Should we use [BEM: block__element--modifier](https://css-tricks.com/bem-101/) for our stylesheet classes?

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +4. Keep indentation/nesting to a minimum. Maximum suggested nesting is 5 layers.
I think 5 is just some reasonable number so that you nest a bit without running the risk of ending up in nesting hell.

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +        & .mx_MyFoo_avatar { // instead of &_avatar
Resolving this conversation because the example is correct. If anyone wants changes drop a comment.

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
**Vote:** We should use `lowerCamelCase` names for our stylesheet variables

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
**Vote:** We should use `kebab-case` names for our stylesheet variables

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +9. Use and define generic mixins when reusing styles a lot.
**Vote:** We should not encourage the use of mixins in our stylesheets.

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +## (S)CSS
Added to the doc

2022-07-18 15:16 UTC, weeman1337 commented on web-code-style.md
> +## (S)CSS
Done

2022-07-18 15:17 UTC, weeman1337 commented on web-code-style.md
> +    const val = a > b
You can vote for it here: https://github.com/vector-im/element-meta/pull/216/files#r923428875

2022-07-18 15:59 UTC, dbkr commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
1. I thought we already did prefer double quotes
2. Prettier's default s double quotes, so I'd go with that unless there's a good reason not to

2022-07-18 16:02 UTC, dbkr commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
This would be another thing moving further away from Prettier style, so purely on that basis I'd say no.

2022-07-18 16:11 UTC, dbkr commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
This is an annoying one because iirc we've been fairly good at sticking to this one so there's significant precedent. Prettier, however, does not pad them.

2022-07-18 16:17 UTC, weeman1337 commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
Going to add a third option here:

**Vote:** Keep it as it is „Curly braces within JSX should be padded with a space, however properties on those components should not.“

:+1: yes ; :-1: no ; :eyes: don't care

2022-07-19 10:49 UTC, luixxiul commented on web-code-style.md
> +4. Keep indentation/nesting to a minimum. Maximum suggested nesting is 5 layers.
I think so too, therefore I am not sure why not putting it into `Keep indentation/nesting to a reasonable number`.

2022-07-27 19:45 UTC, duxovni reviewed
(Clearing my Changes Requested flag since those are all resolved)

2022-07-27 19:47 UTC, duxovni approved these changes
(Hm, do I need to specifically approve in order to clear that?)

2022-08-04 08:52 UTC, weeman1337 commented on web-code-style.md
> +13. Curly braces within JSX should be padded with a space, however properties on those components should not.
Vote conclusion: We will leave it as described.

2022-08-04 08:59 UTC, weeman1337 commented on web-code-style.md
> +7. Non-shared variables should use $lowerCamelCase. Shared variables use $dashed-naming.
Vote conclusion: We keep it as described.

2022-08-04 09:00 UTC, weeman1337 commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
Vote conclusion: We keep it as described.

2022-08-04 09:02 UTC, weeman1337 commented on web-code-style.md
> +    3. mx_MyFoo_avatar--user
Closing this as a conclusion to the vote here: https://github.com/vector-im/element-meta/pull/216/files#r852730907 Using BEM now did not get any vote.

This does not mean we can have another discussion about this in the future.

2022-08-04 09:26 UTC, weeman1337 commented on web-code-style.md
> +## TypeScript / JavaScript {#typescript-javascript}
Vote result: Going for double quotes

2022-08-04 09:28 UTC, weeman1337 commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
Vote result: Tie. Send to discussion

2022-08-04 09:32 UTC, weeman1337 commented on web-code-style.md
> +# Element Web/Desktop code style
Vote results:
- `React.Component::forceUpdate` should not be used
- async-await should be preferred to promise-chaining

2022-08-04 09:39 UTC, weeman1337 commented on web-code-style.md
> +9. Use and define generic mixins when reusing styles a lot.
Vote result: Remove this rule

2022-08-05 06:55 UTC, weeman1337 commented on web-code-style.md
> +        return !!arg1 && !!arg2 && !!arg3;
Vote result: Operators at beginning of line

2022-08-11 12:10 UTC, 3nprob commented on web-code-style.md
> +5. When a statement's body is a single line, it may be written without curly braces, so long as the body is placed on the same line as the statement.
Is this open for reconsideration? It can be very easy to have these result in confusion and even bugs if you don't play close attention, especially as clauses grow over time.

I suggest removing this clause and preferring curlied blocks.

2022-08-25 13:00 UTC, weeman1337 commented
## PR list

* https://github.com/vector-im/element-web/pull/23153
* https://github.com/matrix-org/matrix-js-sdk/pull/2621
* https://github.com/matrix-org/matrix-react-sdk/pull/9220
* https://github.com/matrix-org/eslint-plugin-matrix-org/pull/30

2022-09-01 11:52 UTC, weeman1337 commented
The new code style has been merged and can be found [here](https://github.com/vector-im/element-web/blob/develop/code_style.md).

2022-09-01 11:52 UTC, closed without merging

2022-09-01 11:53 UTC, weeman1337 commented on web-code-style.md
> +This code style applies to projects which the element-web team directly maintains or is reasonably
See https://github.com/vector-im/element-web/blob/develop/code_style.md